cell_size: 50
grid_size: 4
robotLoc: "pos-1-1"
goalLoc: "pos-4-4"

boxes:
- "box1"
- "box2"
- "box3"
- "box4"

balls:
- "ball1"
- "ball2"
- "ball3"
- "ball4"

boxLocs:
- "pos-2-2"
- "pos-4-2"
- "pos-3-4"
- "pos-4-3"

ballLocs:
- "pos-1-3"
- "pos-3-3"
- "pos-1-2"
- "pos-2-1"

directions:
- "dir-east"
- "dir-north"
- "dir-south"
- "dir-northeast"
- "dir-northwest"
- "dir-southeast"
- "dir-southwest"
- "dir-west"

connections:
- "pos-1-1 pos-1-2 dir-east"
- "pos-1-1 pos-2-2 dir-southeast"
- "pos-1-1 pos-2-1 dir-south"
- "pos-1-2 pos-1-1 dir-west"
- "pos-1-2 pos-2-1 dir-southwest"
- "pos-1-2 pos-2-2 dir-south"
- "pos-1-2 pos-2-3 dir-southeast"
- "pos-1-2 pos-1-3 dir-east"
- "pos-1-3 pos-1-2 dir-west"
- "pos-1-3 pos-2-2 dir-southwest"
- "pos-1-3 pos-2-3 dir-south"
- "pos-1-3 pos-2-4 dir-southeast"
- "pos-1-3 pos-1-4 dir-east"
- "pos-1-4 pos-1-3 dir-west"
- "pos-1-4 pos-2-3 dir-southwest"
- "pos-1-4 pos-2-4 dir-south"
- "pos-2-1 pos-1-1 dir-north"
- "pos-2-1 pos-3-1 dir-south"
- "pos-2-1 pos-3-2 dir-southeast"
- "pos-2-1 pos-2-2 dir-east"
- "pos-2-1 pos-1-2 dir-northeast"
- "pos-2-2 pos-1-2 dir-north"
- "pos-2-2 pos-1-1 dir-northwest"
- "pos-2-2 pos-2-1 dir-west"
- "pos-2-2 pos-3-1 dir-southwest"
- "pos-2-2 pos-3-2 dir-south"
- "pos-2-2 pos-3-3 dir-southeast"
- "pos-2-2 pos-2-3 dir-east"
- "pos-2-2 pos-1-3 dir-northeast"
- "pos-2-3 pos-1-3 dir-north"
- "pos-2-3 pos-1-2 dir-northwest"
- "pos-2-3 pos-2-2 dir-west"
- "pos-2-3 pos-3-2 dir-southwest"
- "pos-2-3 pos-3-3 dir-south"
- "pos-2-3 pos-3-4 dir-southeast"
- "pos-2-3 pos-2-4 dir-east"
- "pos-2-3 pos-1-4 dir-northeast"
- "pos-2-4 pos-1-4 dir-north"
- "pos-2-4 pos-1-3 dir-northwest"
- "pos-2-4 pos-2-3 dir-west"
- "pos-2-4 pos-3-3 dir-southwest"
- "pos-2-4 pos-3-4 dir-south"
- "pos-3-1 pos-2-1 dir-north"
- "pos-3-1 pos-4-1 dir-south"
- "pos-3-1 pos-4-2 dir-southeast"
- "pos-3-1 pos-3-2 dir-east"
- "pos-3-1 pos-2-2 dir-northeast"
- "pos-3-2 pos-2-2 dir-north"
- "pos-3-2 pos-2-1 dir-northwest"
- "pos-3-2 pos-3-1 dir-west"
- "pos-3-2 pos-4-1 dir-southwest"
- "pos-3-2 pos-4-2 dir-south"
- "pos-3-2 pos-4-3 dir-southeast"
- "pos-3-2 pos-3-3 dir-east"
- "pos-3-2 pos-2-3 dir-northeast"
- "pos-3-3 pos-2-3 dir-north"
- "pos-3-3 pos-2-2 dir-northwest"
- "pos-3-3 pos-3-2 dir-west"
- "pos-3-3 pos-4-2 dir-southwest"
- "pos-3-3 pos-4-3 dir-south"
- "pos-3-3 pos-4-4 dir-southeast"
- "pos-3-3 pos-3-4 dir-east"
- "pos-3-3 pos-2-4 dir-northeast"
- "pos-3-4 pos-2-4 dir-north"
- "pos-3-4 pos-2-3 dir-northwest"
- "pos-3-4 pos-3-3 dir-west"
- "pos-3-4 pos-4-3 dir-southwest"
- "pos-3-4 pos-4-4 dir-south"
- "pos-4-1 pos-3-1 dir-north"
- "pos-4-1 pos-4-2 dir-east"
- "pos-4-1 pos-3-2 dir-northeast"
- "pos-4-2 pos-3-2 dir-north"
- "pos-4-2 pos-3-1 dir-northwest"
- "pos-4-2 pos-4-1 dir-west"
- "pos-4-2 pos-4-3 dir-east"
- "pos-4-2 pos-3-3 dir-northeast"
- "pos-4-3 pos-3-3 dir-north"
- "pos-4-3 pos-3-2 dir-northwest"
- "pos-4-3 pos-4-2 dir-west"
- "pos-4-3 pos-4-4 dir-east"
- "pos-4-3 pos-3-4 dir-northeast"
- "pos-4-4 pos-3-4 dir-north"
- "pos-4-4 pos-3-3 dir-northwest"
- "pos-4-4 pos-4-3 dir-west"

