cell_size: 0.23
grid_size: 15
robotLoc: "pos-7-3"
goalLoc: "pos-2-2"
robotDir: "dir-north"

boxes:
- "box1"
- "box2"

balls:
- "ball1"

boxLocs:
- "pos-3-3"
- "pos-4-2"

ballLocs:
- "pos-13-13"

directions:
- "dir-east"
- "dir-north"
- "dir-south"
- "dir-west"

leftOf:
- "dir-east dir-north"
- "dir-north dir-west"
- "dir-south dir-east"
- "dir-west dir-south"

connections:
- "pos-1-1 pos-2-1 dir-south"
- "pos-1-1 pos-1-2 dir-east"
- "pos-1-2 pos-2-2 dir-south"
- "pos-1-2 pos-1-1 dir-west"
- "pos-1-2 pos-1-3 dir-east"
- "pos-1-3 pos-2-3 dir-south"
- "pos-1-3 pos-1-2 dir-west"
- "pos-1-3 pos-1-4 dir-east"
- "pos-1-4 pos-2-4 dir-south"
- "pos-1-4 pos-1-3 dir-west"
- "pos-1-4 pos-1-5 dir-east"
- "pos-1-5 pos-2-5 dir-south"
- "pos-1-5 pos-1-4 dir-west"
- "pos-2-1 pos-1-1 dir-north"
- "pos-2-1 pos-3-1 dir-south"
- "pos-2-1 pos-2-2 dir-east"
- "pos-2-2 pos-1-2 dir-north"
- "pos-2-2 pos-3-2 dir-south"
- "pos-2-2 pos-2-1 dir-west"
- "pos-2-2 pos-2-3 dir-east"
- "pos-2-3 pos-1-3 dir-north"
- "pos-2-3 pos-3-3 dir-south"
- "pos-2-3 pos-2-2 dir-west"
- "pos-2-3 pos-2-4 dir-east"
- "pos-2-4 pos-1-4 dir-north"
- "pos-2-4 pos-3-4 dir-south"
- "pos-2-4 pos-2-3 dir-west"
- "pos-2-4 pos-2-5 dir-east"
- "pos-2-5 pos-1-5 dir-north"
- "pos-2-5 pos-3-5 dir-south"
- "pos-2-5 pos-2-4 dir-west"
- "pos-3-1 pos-2-1 dir-north"
- "pos-3-1 pos-4-1 dir-south"
- "pos-3-1 pos-3-2 dir-east"
- "pos-3-2 pos-2-2 dir-north"
- "pos-3-2 pos-4-2 dir-south"
- "pos-3-2 pos-3-1 dir-west"
- "pos-3-2 pos-3-3 dir-east"
- "pos-3-3 pos-2-3 dir-north"
- "pos-3-3 pos-4-3 dir-south"
- "pos-3-3 pos-3-2 dir-west"
- "pos-3-3 pos-3-4 dir-east"
- "pos-3-4 pos-2-4 dir-north"
- "pos-3-4 pos-4-4 dir-south"
- "pos-3-4 pos-3-3 dir-west"
- "pos-3-4 pos-3-5 dir-east"
- "pos-3-5 pos-2-5 dir-north"
- "pos-3-5 pos-4-5 dir-south"
- "pos-3-5 pos-3-4 dir-west"
- "pos-4-1 pos-3-1 dir-north"
- "pos-4-1 pos-5-1 dir-south"
- "pos-4-1 pos-4-2 dir-east"
- "pos-4-2 pos-3-2 dir-north"
- "pos-4-2 pos-5-2 dir-south"
- "pos-4-2 pos-4-1 dir-west"
- "pos-4-2 pos-4-3 dir-east"
- "pos-4-3 pos-3-3 dir-north"
- "pos-4-3 pos-5-3 dir-south"
- "pos-4-3 pos-4-2 dir-west"
- "pos-4-3 pos-4-4 dir-east"
- "pos-4-4 pos-3-4 dir-north"
- "pos-4-4 pos-5-4 dir-south"
- "pos-4-4 pos-4-3 dir-west"
- "pos-4-4 pos-4-5 dir-east"
- "pos-4-5 pos-3-5 dir-north"
- "pos-4-5 pos-5-5 dir-south"
- "pos-4-5 pos-4-4 dir-west"
- "pos-5-1 pos-4-1 dir-north"
- "pos-5-1 pos-6-1 dir-south"
- "pos-5-1 pos-5-2 dir-east"
- "pos-5-2 pos-4-2 dir-north"
- "pos-5-2 pos-6-2 dir-south"
- "pos-5-2 pos-5-1 dir-west"
- "pos-5-2 pos-5-3 dir-east"
- "pos-5-3 pos-4-3 dir-north"
- "pos-5-3 pos-6-3 dir-south"
- "pos-5-3 pos-5-2 dir-west"
- "pos-5-3 pos-5-4 dir-east"
- "pos-5-4 pos-4-4 dir-north"
- "pos-5-4 pos-6-4 dir-south"
- "pos-5-4 pos-5-3 dir-west"
- "pos-5-4 pos-5-5 dir-east"
- "pos-5-5 pos-4-5 dir-north"
- "pos-5-5 pos-6-5 dir-south"
- "pos-5-5 pos-5-4 dir-west"
- "pos-6-1 pos-5-1 dir-north"
- "pos-6-1 pos-7-1 dir-south"
- "pos-6-1 pos-6-2 dir-east"
- "pos-6-2 pos-5-2 dir-north"
- "pos-6-2 pos-7-2 dir-south"
- "pos-6-2 pos-6-1 dir-west"
- "pos-6-2 pos-6-3 dir-east"
- "pos-6-3 pos-5-3 dir-north"
- "pos-6-3 pos-7-3 dir-south"
- "pos-6-3 pos-6-2 dir-west"
- "pos-6-3 pos-6-4 dir-east"
- "pos-6-4 pos-5-4 dir-north"
- "pos-6-4 pos-7-4 dir-south"
- "pos-6-4 pos-6-3 dir-west"
- "pos-6-4 pos-6-5 dir-east"
- "pos-6-5 pos-5-5 dir-north"
- "pos-6-5 pos-7-5 dir-south"
- "pos-6-5 pos-6-4 dir-west"
- "pos-7-1 pos-6-1 dir-north"
- "pos-7-1 pos-8-1 dir-south"
- "pos-7-1 pos-7-2 dir-east"
- "pos-7-2 pos-6-2 dir-north"
- "pos-7-2 pos-8-2 dir-south"
- "pos-7-2 pos-7-1 dir-west"
- "pos-7-2 pos-7-3 dir-east"
- "pos-7-3 pos-6-3 dir-north"
- "pos-7-3 pos-8-3 dir-south"
- "pos-7-3 pos-7-2 dir-west"
- "pos-7-3 pos-7-4 dir-east"
- "pos-7-4 pos-6-4 dir-north"
- "pos-7-4 pos-8-4 dir-south"
- "pos-7-4 pos-7-3 dir-west"
- "pos-7-4 pos-7-5 dir-east"
- "pos-7-5 pos-6-5 dir-north"
- "pos-7-5 pos-8-5 dir-south"
- "pos-7-5 pos-7-4 dir-west"
- "pos-8-1 pos-7-1 dir-north"
- "pos-8-1 pos-9-1 dir-south"
- "pos-8-1 pos-8-2 dir-east"
- "pos-8-2 pos-7-2 dir-north"
- "pos-8-2 pos-9-2 dir-south"
- "pos-8-2 pos-8-1 dir-west"
- "pos-8-2 pos-8-3 dir-east"
- "pos-8-3 pos-7-3 dir-north"
- "pos-8-3 pos-9-3 dir-south"
- "pos-8-3 pos-8-2 dir-west"
- "pos-8-3 pos-8-4 dir-east"
- "pos-8-4 pos-7-4 dir-north"
- "pos-8-4 pos-9-4 dir-south"
- "pos-8-4 pos-8-3 dir-west"
- "pos-8-4 pos-8-5 dir-east"
- "pos-8-5 pos-7-5 dir-north"
- "pos-8-5 pos-9-5 dir-south"
- "pos-8-5 pos-8-4 dir-west"
- "pos-9-1 pos-8-1 dir-north"
- "pos-9-1 pos-10-1 dir-south"
- "pos-9-1 pos-9-2 dir-east"
- "pos-9-2 pos-8-2 dir-north"
- "pos-9-2 pos-10-2 dir-south"
- "pos-9-2 pos-9-1 dir-west"
- "pos-9-2 pos-9-3 dir-east"
- "pos-9-3 pos-8-3 dir-north"
- "pos-9-3 pos-10-3 dir-south"
- "pos-9-3 pos-9-2 dir-west"
- "pos-9-3 pos-9-4 dir-east"
- "pos-9-4 pos-8-4 dir-north"
- "pos-9-4 pos-10-4 dir-south"
- "pos-9-4 pos-9-3 dir-west"
- "pos-9-4 pos-9-5 dir-east"
- "pos-9-5 pos-8-5 dir-north"
- "pos-9-5 pos-10-5 dir-south"
- "pos-9-5 pos-9-4 dir-west"
- "pos-10-1 pos-9-1 dir-north"
- "pos-10-1 pos-11-1 dir-south"
- "pos-10-1 pos-10-2 dir-east"
- "pos-10-2 pos-9-2 dir-north"
- "pos-10-2 pos-11-2 dir-south"
- "pos-10-2 pos-10-1 dir-west"
- "pos-10-2 pos-10-3 dir-east"
- "pos-10-3 pos-9-3 dir-north"
- "pos-10-3 pos-11-3 dir-south"
- "pos-10-3 pos-10-2 dir-west"
- "pos-10-3 pos-10-4 dir-east"
- "pos-10-4 pos-9-4 dir-north"
- "pos-10-4 pos-11-4 dir-south"
- "pos-10-4 pos-10-3 dir-west"
- "pos-10-4 pos-10-5 dir-east"
- "pos-10-5 pos-9-5 dir-north"
- "pos-10-5 pos-11-5 dir-south"
- "pos-10-5 pos-10-4 dir-west"
- "pos-11-1 pos-10-1 dir-north"
- "pos-11-1 pos-12-1 dir-south"
- "pos-11-1 pos-11-2 dir-east"
- "pos-11-2 pos-10-2 dir-north"
- "pos-11-2 pos-12-2 dir-south"
- "pos-11-2 pos-11-1 dir-west"
- "pos-11-2 pos-11-3 dir-east"
- "pos-11-3 pos-10-3 dir-north"
- "pos-11-3 pos-12-3 dir-south"
- "pos-11-3 pos-11-2 dir-west"
- "pos-11-3 pos-11-4 dir-east"
- "pos-11-4 pos-10-4 dir-north"
- "pos-11-4 pos-12-4 dir-south"
- "pos-11-4 pos-11-3 dir-west"
- "pos-11-4 pos-11-5 dir-east"
- "pos-11-5 pos-10-5 dir-north"
- "pos-11-5 pos-12-5 dir-south"
- "pos-11-5 pos-11-4 dir-west"
- "pos-12-1 pos-11-1 dir-north"
- "pos-12-1 pos-13-1 dir-south"
- "pos-12-1 pos-12-2 dir-east"
- "pos-12-2 pos-11-2 dir-north"
- "pos-12-2 pos-13-2 dir-south"
- "pos-12-2 pos-12-1 dir-west"
- "pos-12-2 pos-12-3 dir-east"
- "pos-12-3 pos-11-3 dir-north"
- "pos-12-3 pos-13-3 dir-south"
- "pos-12-3 pos-12-2 dir-west"
- "pos-12-3 pos-12-4 dir-east"
- "pos-12-4 pos-11-4 dir-north"
- "pos-12-4 pos-13-4 dir-south"
- "pos-12-4 pos-12-3 dir-west"
- "pos-12-4 pos-12-5 dir-east"
- "pos-12-5 pos-11-5 dir-north"
- "pos-12-5 pos-13-5 dir-south"
- "pos-12-5 pos-12-4 dir-west"
- "pos-13-1 pos-12-1 dir-north"
- "pos-13-1 pos-14-1 dir-south"
- "pos-13-1 pos-13-2 dir-east"
- "pos-13-2 pos-12-2 dir-north"
- "pos-13-2 pos-14-2 dir-south"
- "pos-13-2 pos-13-1 dir-west"
- "pos-13-2 pos-13-3 dir-east"
- "pos-13-3 pos-12-3 dir-north"
- "pos-13-3 pos-14-3 dir-south"
- "pos-13-3 pos-13-2 dir-west"
- "pos-13-3 pos-13-4 dir-east"
- "pos-13-4 pos-12-4 dir-north"
- "pos-13-4 pos-14-4 dir-south"
- "pos-13-4 pos-13-3 dir-west"
- "pos-13-4 pos-13-5 dir-east"
- "pos-13-5 pos-12-5 dir-north"
- "pos-13-5 pos-14-5 dir-south"
- "pos-13-5 pos-13-4 dir-west"
- "pos-14-1 pos-13-1 dir-north"
- "pos-14-1 pos-15-1 dir-south"
- "pos-14-1 pos-14-2 dir-east"
- "pos-14-2 pos-13-2 dir-north"
- "pos-14-2 pos-15-2 dir-south"
- "pos-14-2 pos-14-1 dir-west"
- "pos-14-2 pos-14-3 dir-east"
- "pos-14-3 pos-13-3 dir-north"
- "pos-14-3 pos-15-3 dir-south"
- "pos-14-3 pos-14-2 dir-west"
- "pos-14-3 pos-14-4 dir-east"
- "pos-14-4 pos-13-4 dir-north"
- "pos-14-4 pos-15-4 dir-south"
- "pos-14-4 pos-14-3 dir-west"
- "pos-14-4 pos-14-5 dir-east"
- "pos-14-5 pos-13-5 dir-north"
- "pos-14-5 pos-15-5 dir-south"
- "pos-14-5 pos-14-4 dir-west"
- "pos-15-1 pos-14-1 dir-north"
- "pos-15-1 pos-15-2 dir-east"
- "pos-15-2 pos-14-2 dir-north"
- "pos-15-2 pos-15-1 dir-west"
- "pos-15-2 pos-15-3 dir-east"
- "pos-15-3 pos-14-3 dir-north"
- "pos-15-3 pos-15-2 dir-west"
- "pos-15-3 pos-15-4 dir-east"
- "pos-15-4 pos-14-4 dir-north"
- "pos-15-4 pos-15-3 dir-west"
- "pos-15-4 pos-15-5 dir-east"
- "pos-15-5 pos-14-5 dir-north"
- "pos-15-5 pos-15-4 dir-west"
