state_creators:
    - nao_actions/state_creator_robot_pose robot_location location at-base location
goal_creators:
    - nao_actions/goal_creator_tidyup_objects
action_executors:
    - nao_actions/action_executor_pickup pickup /nao_msgs/pickup_action_server
    - nao_actions/action_executor_drop drop /nao_msgs/drop_action_server
    - nao_actions/action_executor_walk walk /nao_msgs/walk_action_server
    - nao_actions/action_executor_kick kick /nao_msgs/kick_action_server
