(define (domain nao-world)
  (:requirements :typing :durative-actions)
  (:types thing location direction - object
          robot box ball - thing)
  (:predicates (clear ?l - location)
	       (at ?t - thing ?l - location)
	       (at-goal ?s - robot)
	       (IS-GOAL ?l - location)
	       (IS-NONGOAL ?l - location)
               (MOVE-DIR ?from ?to - location ?dir - direction)
	       (HandEmpty ?r - robot)
	       (Holding ?r - robot ?b - box))

  (:durative-action move
   :parameters (?p - robot ?from ?to - location ?dir - direction)
   :duration  (= ?duration 1)
   :condition (and (at start (at ?p ?from))
                   (at start (clear ?to))
                   (over all (MOVE-DIR ?from ?to ?dir))
                   )
   :effect    (and (at start (not (at ?p ?from)))
                   (at start (not (clear ?to)))
                   (at end (at ?p ?to))
                   (at end (clear ?from))
                   )
   )

  (:durative-action kick
   :parameters (?p - robot ?s - ball
                ?ppos ?from ?to - location
                ?dir - direction)
   :duration (= ?duration 1)
   :condition (and (at start (at ?p ?ppos))
                   (at start (at ?s ?from))
                   (at start (clear ?to))
                   (over all (MOVE-DIR ?ppos ?from ?dir))
                   (over all (MOVE-DIR ?from ?to ?dir)))
                   )
   :effect    (and (at start (not (at ?p ?ppos)))
                   (at start (not (at ?s ?from)))
                   (at start (not (clear ?to)))
                   (at end (at ?p ?from))
                   (at end (at ?s ?to))
                   (at end (clear ?ppos))
                   )
   )

   (:durative-action pickup
   :parameters (?p - robot ?s - box
                ?ppos ?from - location
                ?dir - direction)
   :duration (= ?duration 1)
   :condition (and (at start (at ?p ?ppos))
                   (at start (at ?s ?from))
                   (over all (MOVE-DIR ?ppos ?from ?dir))
		   (HandEmpty ?p))
                   )
   :effect    (and (at start (not (at ?p ?ppos)))
                   (at start (not (at ?s ?from)))
                   (at end (at ?p ?from))
                   (at end (clear ?ppos))
		   (at end (not (HandEmpty ?p)))
		   (at end (Holding ?p ?s))
                   )
   )

   (:durative-action putdown
   :parameters (?p - robot ?s - box
                ?ppos ?to - location
                ?dir - direction)
   :duration (= ?duration 1)
   :condition (and (at start (at ?p ?ppos))
                   (at start (clear ?to))
		   (at start (Holding ?p ?s))
                   (over all (MOVE-DIR ?ppos ?to ?dir))
                   )
   :effect    (and (at start (not (clear ?to)))
                   (at end (at ?p ?ppos))
                   (at end (at ?s ?to))
                   (at end (not (Holding ?p ?s)))
		   (at end (HandEmpty ?p))
		   )
   )
  
)
